### PR TITLE
Update ALS for Factorio 0.0.13

### PR DESCRIPTION
**Pull request by jakimfett**
Remove deprecated 'defines', refactor game.get_surface(), and set item/loot distances.

### CODE REVIEW

**Comment by Mijago** [comment]
I guess there is more stuff missing, because opening the GUI results in this:
http://prntscr.com/bpuf37

**Comment by jakimfett** [comment]
@Mijago can I get you to upload your world and the mods you're using so I can test this?

**Comment by Radje** [comment]
@jakimfett I get the same error as @Mijago.
[Save file and mods folder](https://www.dropbox.com/s/p50rnbjbrwr7yp9/Save%20and%20Mods.rar?dl=0)

Thanks for the help!

Edit. I actually just realized that that save point does not have ALS researched yet. But when selected it should be done within a minute or so. I will see if I can get a "better" save later today

**Comment by Mijago** [comment]
Sorry, I changed my mod-setting since then and did not have a backup.

 Next time i'll do one :) I hope you get the fix, I just do not enough time currently. 

I send this via the mail-reply as a test. I hope it works ;)

**Comment by DarkHelmet433** [comment]
I've had the same problem too.  For me the problem was the GUI was malfunctioning..  eg: open the search and it wouldn't ever update.  In order to try and reset things, I saved, uninstalled the modified mod, loaded, saved again, reinstalled the mod.

When I reloaded I'd see the research item for ALS.  On researching it the gui button appears.  If I press the button, I see the exact error reported above.

The patched mod was already malfunctioning before I tried this though - search wasn't working.

**Comment by anoutsider** [comment]
Hey,
Sorry guys for the delayed updates and thanks @jakimfett for stepping up.

Recently moved to a new job and a new city so been busy setteling in, i'll work on updating the mod and fixing all these issues this week.

**Comment by jakimfett** [comment]
@anoutsider no worries, glad to do a bit to contribute! 

I'll have a bit of time tomorrow to poke the problems @DarkHelmet433 and @Radje and @Mijago are having, and will update the PR with whatever fixes end up happening.

**Comment by DarkHelmet433** [comment]
Hey.  I found the remaining gui bug.

change all
ipairs(game.players)
to
pairs(game.players)

because of
0.13.0 release notes wrote:
Changed game.players, game.surfaces, game.entity_prototypes, game.item_prototypes, game.fluid_prototypes, force.recipes, force,technologies to use custom access + iterator objects for improved performance.

Without this, the player iterations are coming up empty.  With this the search interface works again and the remaining nil errors that I was having went away.

To be clear, I reverted my other changes and am running with the pull request from @jakimfett plus s/ipairs(game.players)/pairs(game.players)/ and no other tweaks.

**Comment by Mijago** [comment]
Nice! I'll try  later. Thank you!

**Comment by jakimfett** [comment]
...yeah, sorry, I did approximately zero development this weekend because I totally wasn't playing Pokemon Go.

**Comment by jakimfett** [comment]
Also, @DarkHelmet433 thanks for posting the info. That's probably why #14 is happening.

**Comment by EpicGamingVideos** [comment]
I did all the cahnges listed here but after researching i dont have the icon to craft.

**Comment by AndrisBorbas** [comment]
I get an error message on clicking normal items: Error while running the event handler: **advanced-logistics-system**/control.lua:1237: bad argument #1 to 'match' (string expected, got nil)
And the 1237 line is this:     local left,num,right = string.match(n,'^([^%d]_%d)(%d_)(.-)$')

**Comment by Diedel72** [comment]
I got the same error in line 1237, but i am not sure why the function gets a nil number.

A quick fix that seems to work for now is just returning an empty string on a nil number.

--- Format numbers
function number_format(n) -- credit http://richard.warburton.it
    if n == nil then
        return ""
    else
        local left,num,right = string.match(n,'^([^%d]_%d)(%d_)(.-)$')  
        return left..(num:reverse():gsub('(%d%d%d)','%1,'):reverse())..right
    end
end

**Comment by smickles** [comment]
I'm getting a
 `Error while running the event handler: __advanced-logistics-system__/gui/main.lua:60: attempt to index field '?' (a nil value)`
when I click the button to open the interface after researching the tech. Anyone know what's going on there?

**Comment by HammerPiano** [comment]
Hi everyone
I added the factorio version in the info.json file, because of 0.13 and whenever I launch factorio, while loading the prototypes I get:
Error while loading entity prototype "Is-controller" (player): No suck node(item_pickup_distance)
Modifications: advanced-logistics-system
I am a beginner modder, know almost nothing about modding.

**Comment by Danielv123** [comment]
@HammerPiano when fixing things, consider submitting a pull request/forking the project if you got it to work. I am sure someone would be very interested :)

**Comment by HammerPiano** [comment]
@Danielv123, I forked this project and changed info.json according to the factorio team(added factorio version). Here is the link to my fork with the change:
https://github.com/HammerPiano/advanced-logistics-system/blob/master/info.json

**Comment by anoutsider** [comment]
Thank you all for the help, due to conflicts and other updates to the code i'll be closing this pull request as it's no longer required.

**Pull request closed without merging**
